# Generated by Django 4.1.3 on 2023-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomRespo', models.CharField(max_length=25)),
                ('PrenomRespo', models.CharField(max_length=20)),
                ('Genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('DateNaiss', models.DateField()),
            ],
        ),
    ]
