# Generated by Django 4.1.3 on 2023-01-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMateriel', models.CharField(max_length=40)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agence')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsable')),
            ],
        ),
    ]
