# Generated by Django 4.1.3 on 2023-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeoper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTypeoper', models.CharField(max_length=25)),
            ],
        ),
    ]
