# Generated by Django 4.1.3 on 2023-01-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_typeoper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomClient', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=60)),
                ('Telephone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=60)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsable')),
            ],
        ),
    ]
