# Generated by Django 4.1.3 on 2023-01-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailcommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.IntegerField()),
                ('PrixUnit', models.IntegerField()),
                ('NombreJour', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiel')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsable')),
                ('typeoper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeoper')),
            ],
        ),
    ]
