# Generated by Django 4.1.3 on 2023-01-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_detailcommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomFournisseur', models.CharField(max_length=35)),
                ('Adresse', models.CharField(max_length=35)),
                ('Telephone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=35)),
            ],
        ),
    ]
