# Generated by Django 4.1.3 on 2023-01-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_approvisionnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantitebrute', models.IntegerField()),
                ('Quantiteloue', models.IntegerField()),
                ('Quantitestock', models.IntegerField()),
                ('Dateoperation', models.DateField()),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiel')),
                ('typeoper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeoper')),
            ],
        ),
    ]
