# Generated by Django 4.1.3 on 2023-01-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailapprovionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.IntegerField()),
                ('Prixunit', models.IntegerField()),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.approvisionnement')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiel')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsable')),
            ],
        ),
    ]
